packages:
  - packages/*
  - components/**
  - examples/**
  - benchmarks/*
  - '!**/test/**'

ignoredBuiltDependencies:
  - '@bufbuild/buf'

minimumReleaseAge: 7200

minimumReleaseAgeExclude:
  - typescript

onlyBuiltDependencies:
  - '@nestjs/core'
